micronaut:
  server:
    port: 8001
    cors:
      enabled: true
  application:
    name: projectMicronautApp
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES
#jpa.default.properties.hibernate.hbm2ddl.auto: update
